### ISSUE TITLE
所以你们有没有解决在学校外面没法访问 API 的问题

### ISSUE THREAD

**Issue by JingBh** [larryyan/IndoorRobot#1]
如果没有的话，可以试试这个 Mock Server：
https://d1808bfb-7b8e-4f9a-936b-75c19663032f.mock.pstmn.io

**Comment by larryyan** [comment]
感谢大佬提供的api，目前已经改进去了

**Comment by JingBh** [comment]
但是你用的时候会发现这个 API 只有我在学校的时候抓的两条测试数据：《红楼梦》和“毛泽东” 🤪
